### ISSUE TITLE
konflikt dołączonych zasobów

### ISSUE THREAD

**Issue by kamilwlf** [blipinsk/RecyclerViewHeader#1]
Po pierwsze proponuje zmienić minSdkVersion.
Po drugie usuń wszelkie niepotrzebne elementy, np. ikonki.
Po trzecie zaktualizuj wersję RecyclerView do

compile 'com.android.support:appcompat-v7:22.0.0'
compile 'com.android.support:recyclerview-v7:22.0.0'

teraz używasz 7.21

```:app:processDebugManifest
Error:(17, 9) Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:17:9
	is also present at com.bartoszlipinski.recyclerviewheader:library:1.0.1:13:9 value=(@drawable/ic_launcher)
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:15:5 to override
C:\Users\xxx\app\src\main\AndroidManifest.xml:0:0 Error:
	uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library xxaar\com.bartoszlipinski.recyclerviewheader\library\1.0.1\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.bartoszlipinski.recyclerviewheader" to force usage
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs
Information:BUILD FAILED
Information:Total time: 5.768 secs
Information:2 errors```

**Comment by blipinsk** [comment]
Dzięki za przypomnienie.

 * Niepotrzebne rzeczy usunięte - już nie powinieneś mieć konfliktu
 * Wersje `Support Libraries` uaktualnione
 * Wersja `minSdk` zmniejszona (niestety muszę mieć minimalnie 11, ze względu na aktualnie wykorzystywane `setTranslationY(...)`)

Pozdrawiam
Bartek
