### ISSUE TITLE
Swipe to Refresh gets activated when scrolled to end of Recycler view and Scrolling up

### ISSUE THREAD

**Issue by stripathi669** [blipinsk/RecyclerViewHeader#10]
I have a Relative layout that contains a Framelayout and Linearlayout. The framelayout contains Recycler view and Recycler Header. A swipe to refresh layout encloses all of this.

Now my problem is: When I scroll to bottom of recycler view, and start scrolling up, Swipe to Refresh gets activated instead of Recycler view scrolling up. If I remove your wonderful Recycler header, everything works fine (except the part that I now won't have an header.)

What possibly could be going wrong ?

**Comment by blipinsk** [comment]
It's probably due to to the fact that your Swipe to refresh layout also uses `onScrollListener` of the `RecyclerView`. Can you provide any more details about the Swipe to refresh layout you're using?

**Comment by Dadoufi** [comment]
After the header is attached to your recycler view, the first item of your list is no longer at the top of your recycler view's layout manager.

So after the first scroll down you should take into account the height of your header when you are checking for the top on your onScrollListener.

**Comment by stripathi669** [comment]
@blipinsk : I am using this particular library: https://github.com/OrangeGangsters/SwipyRefreshLayout

@Dadoufi : I will try out your suggestion.

**Comment by stripathi669** [comment]
Hi,

I solved the problem using a onScrollListener.

My listener disables pull to refresh is scroll is not touching the top. Now its working all right.
