### ISSUE TITLE
Cannot Scroll by touching the header

### ISSUE THREAD

**Issue by stripathi669** [blipinsk/RecyclerViewHeader#12]
Hi, 

I am facing a very strange issue. My header is a Linear Layout wrapped in Recycle view header. The layout contains several clickable elements.

Now, I am facing two strange issues: 

1. I cannot scroll the recycle view while touching the header.
2. If I add several elements one-by-one to recycle view, scroll away towards end, come back up, the header SOMETIMES disappears. This doesn't happen every time, only sometimes.

Let me know if you need any more details regarding how to reproduce the error.

**Comment by blipinsk** [comment]
Fixed in the 2.0.0 Version.
