### ISSUE TITLE
Header ClickListener

### ISSUE THREAD

**Issue by kioko** [blipinsk/RecyclerViewHeader#13]
How do you make the header clickable?

**Comment by blipinsk** [comment]
Just to clarify:
a) you wanna know how to add an `OnClickListener` to the whole `header`?
b) you've created a header and you're not able to click any of its components?

**Comment by kioko** [comment]
I want to know how to add OnClickListener on the entire header.

**Comment by Shubham1992** [comment]
just add onClickListener to the layout u are using as the header.. I guess that will work fine

**Comment by jlwatkins** [comment]
I'm trying to do the same thing. Is there something wrong with doing what I am doing here? I declare the header on the top. and set the longclicker before attachTo. They are long clickable, but I never get any feedback. I have many other buttons which work fine. Something happens to this header after attachTo I believe. 

![image](https://cloud.githubusercontent.com/assets/4500134/10464112/16740610-71b6-11e5-9b4d-836f61a3134d.png)

**Comment by ShubhamSmartprix** [comment]
same problem with my code too...no response on onClickListener/onTouchListener .... any solution? @blipinsk

**Comment by jlwatkins** [comment]
It helped when I turned on the listener after it is attached to the view. Also make sure it isn't "behind" anything in your xml file with fill parents vs wrap parents. just a hint @ShubhamSmartprix

**Comment by ShubhamSmartprix** [comment]
thnx a lot man..it worked.. The header was actually "behind" the recyclrview in xml. fixed it...
but now I gotta figure out how to make recyclerview scroll on sliding fingure up/dwn on header area.. @jlwatkins

**Comment by jlwatkins** [comment]
No problem. Good luck sounds like you going to have to read some of the code for the LinearLayoutManager, RecyclerViewHeader and RecyclerView. I recommend starting with how the .attachTo() function works for header and than digging into how the scrolling works. I haven't figured that out yet. I am having some problems when refreshing this layout, but haven't done anything with making it scroll.

**Comment by blipinsk** [comment]
Guys, after reading your comments I seriously think you're missing the point of the library.

I wrote in `Readme.md`:
>You need to bare in mind that the library is created to be used with relatively simple headers.

And I DO mean that.

If you want to change the behavior of the header, change the way it scrolls, displays stuff etc. you will end up interfering with other parts of the library, generating more and more issues. Let me phrase the quote from readme differently: 
>This library is created to be used with simple headers, no `ViewPagers`, no other scrollable elements, few simple `Views` at max, being displayed and scrolled in a default way. If you don't match any of the requirements -> use `Adapter` that can display multiple types of `Views`.
