### ISSUE TITLE
when the header's height exceed the screen height,can not be displayed in full.

### ISSUE THREAD

**Issue by lovetomorrow** [blipinsk/RecyclerViewHeader#15]
rs

**Comment by jaysowen** [comment]
I have the same issue.

**Comment by SalmanTKhan** [comment]
Anyone found a workaround?

**Comment by blipinsk** [comment]
Just off the top of my head:
try setting `clipChildren` and `clipToPadding` to `false` for`RecyclerViewHeader` and its parent.

**Comment by SalmanTKhan** [comment]
Hey @blipinsk thanks for the library, I don't know if it's because my header isn't a fixed height due to hiding certain aspects when they aren't available, but now the recyclerview overlaps the header at the bottom.

**Comment by blipinsk** [comment]
@SalmanTKhan it happened when you used the workaround?

**Comment by SalmanTKhan** [comment]
Yes, so now the header isn't cut off but if the header is longer than screen size it will overlap with the recyclerview content.
When header is close to screen size:
![device-2015-07-23-144320](https://cloud.githubusercontent.com/assets/3139467/8859087/2eb39284-3149-11e5-8c9b-e96116019712.png)
When header isn't as long:
![device-2015-07-23-144405](https://cloud.githubusercontent.com/assets/3139467/8859125/5c775e8a-3149-11e5-94f4-b5b3b1675ec5.png)

**Comment by blipinsk** [comment]
I need to make some tests on this issue, but I'm afraid we're reaching another limitation of this *hacky*-approach `RecyclerView` header.

**Comment by ZhangPeibin** [comment]
how to solve this?

**Comment by blipinsk** [comment]
Well... I'm not sure. I was testing that yesterday and it was working correctly for me as long as I wasn't using `reversed` `LayoutManager` (setup: *header-already-aligned approach*; `RecyclerViewHeader` with a fixed, bigger than screen dimension, height; **without** previously mentioned `clipToPadding` and `clipChildren` set to false).

**Comment by MaAnQing** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6247142/11581191/3f752962-9a7a-11e5-80f7-807401bfa831.jpg)
![screenshot 1](https://cloud.githubusercontent.com/assets/6247142/11581197/49a9edf0-9a7a-11e5-9550-4349b50440e5.jpg)

**Comment by blipinsk** [comment]
@MaAnQing I'm sorry but I don't think this refers to the issue specified here.

**Comment by Carpten** [comment]
I have the same issue.

**Comment by blipinsk** [comment]
Fixed in the 2.0.0 Version.

**Comment by yasir-citrusbits** [comment]
I fixed this issue, just replace the header height from match_parent to wrap_content
