### ISSUE TITLE
button or spinner not clickable

### ISSUE THREAD

**Issue by rehacktive** [blipinsk/RecyclerViewHeader#18]
Hi,
I've tried to set a button or a spinner on the header, but they appear not clickable.
Is it a known issue/behaviour?

thanks

**Comment by blipinsk** [comment]
Hi,
which approach do you use to setup your `RecyclerViewHeader`?
Are you sure its above (z-wise) your `RecyclerView`?

**Comment by rehacktive** [comment]
this is my layout:

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

    <com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader
        android:id="@+id/header"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >

        <ImageView
            android:id="@+id/header_image"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop"
            android:src="@drawable/home_1"
            android:layout_above="@+id/include" />

        <include layout="@layout/header1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:id="@+id/include" />

    </com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader>

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipe_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    <com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    </android.support.v4.widget.SwipeRefreshLayout>

</FrameLayout>

and inside the layout "header1" I've tried to put a button or a spinner. With TextViews it's all okay.

Any hint?

**Comment by blipinsk** [comment]
Ok, so as I expected, your `RecyclerViewHeader` is below your `RecyclerView` (z-order-wise).
Change the order of your layout, (probably) like so:

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipe_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

    <com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView
        android:id="@+id/recyclerview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

    </android.support.v4.widget.SwipeRefreshLayout>

    <com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader
        android:id="@+id/header"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent" >

        <ImageView
            android:id="@+id/header_image"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:scaleType="centerCrop"
            android:src="@drawable/home_1"
            android:layout_above="@+id/include" />

        <include layout="@layout/header1"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_alignParentBottom="true"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true"
            android:id="@+id/include" />

    </com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader>

("probably" because you didnt post your entire layout, just a fragment of it, and I don't know the specifics of this `RecyclerView`)
