### ISSUE TITLE
SwipeRefreshLayout Can't use with RecyclerView

### ISSUE THREAD

**Issue by hwangjr** [blipinsk/RecyclerViewHeader#19]
I use RecyclerView with SwipeRefreshLayout and get this exception:
``` java
java.lang.IllegalStateException: Currently, NOT already aligned RecyclerViewHeader can only be used for RecyclerView with a parent of one of types: LinearLayout, FrameLayout, RelativeLayout.
```

Unsupport for SwipeRefreshLayout?
source code:
``` java

    private void validateRecycler(RecyclerView recycler, boolean headerAlreadyAligned) {
        RecyclerView.LayoutManager layoutManager = recycler.getLayoutManager();
        if (layoutManager == null) {
            throw new IllegalStateException("Be sure to call RecyclerViewHeader constructor after setting your RecyclerView's LayoutManager.");
        } else if (layoutManager.getClass() != LinearLayoutManager.class    //not using instanceof on purpose
                && layoutManager.getClass() != GridLayoutManager.class
                && !(layoutManager instanceof StaggeredGridLayoutManager)) {
            throw new IllegalArgumentException("Currently RecyclerViewHeader supports only LinearLayoutManager, GridLayoutManager and StaggeredGridLayoutManager.");
        }

        if (layoutManager instanceof LinearLayoutManager) {
            if (((LinearLayoutManager) layoutManager).getOrientation() != LinearLayoutManager.VERTICAL) {
                throw new IllegalArgumentException("Currently RecyclerViewHeader supports only VERTICAL orientation LayoutManagers.");
            }
        } else if (layoutManager instanceof StaggeredGridLayoutManager) {
            if (((StaggeredGridLayoutManager) layoutManager).getOrientation() != StaggeredGridLayoutManager.VERTICAL) {
                throw new IllegalArgumentException("Currently RecyclerViewHeader supports only VERTICAL orientation StaggeredGridLayoutManagers.");
            }
        }

        if (!headerAlreadyAligned) {
            ViewParent parent = recycler.getParent();
            if (parent != null &&
                    !(parent instanceof LinearLayout) &&
                    !(parent instanceof FrameLayout) &&
                    !(parent instanceof RelativeLayout)) {
                throw new IllegalStateException("Currently, NOT already aligned RecyclerViewHeader " +
                        "can only be used for RecyclerView with a parent of one of types: LinearLayout, FrameLayout, RelativeLayout.");
            }
        }
    }
```

**Comment by blipinsk** [comment]
First of all, try exactly what the `Exception` suggests you to: try **Header-already-aligned approach**. And tell me if it solves your issue :smirk:

**Comment by blipinsk** [comment]
Did it solve your issue? Can I close it?

**Comment by hwangjr** [comment]
i just add the header myself.. because i use SwipeRefreshLayout to refresh the view..
In fact, i think most people use SwipeRefreshLayout to refresh they view, so will the SwipeRefreshLayout view to be supported further?

**Comment by Antpachon** [comment]
This works for me with Header-already-aligned approach

<android.support.v4.widget.SwipeRefreshLayout>
    <FrameLayout>
        <android.support.v7.widget.RecyclerView/>
        <com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader/>
  </FrameLayout>
</android.support.v4.widget.SwipeRefreshLayout>

**Comment by hwangjr** [comment]
ok, can try the solution @Antpachon  supported. i close this issue.

**Comment by blipinsk** [comment]
@hwangjr, I told you to try **header-already-aligned" approach on the 29th of july. Shame you couldn't try that back then :(

**Comment by hwangjr** [comment]
@blipinsk , it's my fault.. i miss look the **header-already-aligned** on README.md and try to found it on branch, and then add header myself..
In fact, my header view has a little complex, like multiple focusable elements etc.. so finally i add a view type to RecyclerView.Adapter.
anyway, i will try it on my next integration, and add it  to my work board.

**Comment by blipinsk** [comment]
Good you went with the adapter with a header, that was probably the right decision (since you're sayin it was a relatively complicated header). Don't worry about this whole situation, I don't want you to feel obligated to use my library. I just shame that my post back then might have helped you, and you wouldn't have to worry to much about the issue. Nevermind :wink:

**Comment by hwangjr** [comment]
In fact, i am searching for some other solution about list view or recycle view ( include refresh and load more ), do u have some advise?
now i just write this wheel, but it's not stable, so i want to find a stable, extendable solution~~

other topic, do u have an app template for the rapid development?

**Comment by Antpachon** [comment]
What you need is SwipeRefreshLayout , this a guide to implement it
http://antonioleiva.com/swiperefreshlayout/


If you update to the latest version of Androdu Studio, you already have
some templates (Navigation Drawer..)

Cheers,
Antonio.

On 1 September 2015 at 13:35, HwangJR <notifications@github.com> wrote:

> In fact, i am searching for some other solution about list view or recycle
> view ( include refresh and load more ), do u have some advise?
> now i just write this wheel, but it's not stable, so i want to find a
> stable, extendable solution~~
>
> other topic, do u have an app template for the rapid development?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blipinsk/RecyclerViewHeader/issues/19#issuecomment-136699261>
> .
>



-- 

*Strictly private & confidential.Regards, Antonio.*

**Comment by blipinsk** [comment]
While this might be a part of a valuable discussion it doesn't seem to be issue-related. Let me lock it, not to flood it with an off-topic. Thanks.
