### ISSUE TITLE
How to manage z-index of header relative to list items?

### ISSUE THREAD

**Issue by cyberdd3** [blipinsk/RecyclerViewHeader#20]
Is it possible to make list items overlap a header? I want to achieve this result to create parallax effect.
Thanks!

**Comment by blipinsk** [comment]
There are two things you need to consider:

 1. First of all your `Header` won't be clickable (probably - depending on your layouts).
 2. You need to be sure your `Header` is below (z-order-wise) your `RecyclerView`. So use **Header-already-aligned approach** and make sure it's below. More-less like this:

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader
                android:id="@+id/header"
                android:layout_width="match_parent"
                android:layout_height="100dp"
                android:layout_gravity="center_horizontal|top">

                

            </com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader>

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recycler"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal|top" />

        </FrameLayout>

 3. The last thing (and the most difficult one) will be interfering with the most important thing of the library. Scrolling of the `RecyclerViewHeader`. You need to change it properly so it implements parallax effect (so the header scrolls slower than the `RecyclerView`)
