### ISSUE TITLE
Removing an item from the list dinamically misplaces the header

### ISSUE THREAD

**Issue by Antpachon** [blipinsk/RecyclerViewHeader#23]
Removing an item from the list dinamically misplaces the header

**Comment by AlexNsbmr** [comment]
Same problem here, has anyone found any sort of workaround? 

@blipinsk Thanks for this amazing library!

**Comment by OhJayDubya** [comment]
I have found a workaround that only really works if the content in your header stays the same and doesn't need to be updated and that is to have it create only once. This may be only isolated to my issue with it but when I assign the header I just wrap it in an "if statement" and check if it has already been created and if it has when I call "notifyDataSetChanged()" it will ignore the recreation of the header.

boolean flag = false;

if(!flag)  {

            RecyclerViewHeader header = (RecyclerViewHeader)rootView.findViewById(R.id.header);
            header.attachTo(recyclerView, true);
            test = true;
}


A simple solution but a one that works for me as my header doesn't need to be updated each time as it will always have the same content.

**Comment by blipinsk** [comment]
Fixed in the 2.0.0 Version.
