### ISSUE TITLE
Is it possible to header cover items ?

### ISSUE THREAD

**Issue by stasbar** [blipinsk/RecyclerViewHeader#25]
Hello. I want something like this: http://imgur.com/E33eMyz
but when I added header it look like this: http://imgur.com/GMih0z5
header is cropped.

**Comment by blipinsk** [comment]
Try using **Header-already-aligned approach** and setting `clipChildren` and `clipToPadding` to `false` for the `RecyclerViewHeader`.

**Comment by stasbar** [comment]
<com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader
        android:layout_gravity="center_horizontal|top"
        android:id="@+id/header"
        android:layout_height="80dp"
        android:layout_width="match_parent"
        android:clipChildren="false"
        android:clipToPadding="false">
        <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/category_subtitle_root"
            android:layout_width="match_parent"
            android:layout_height="80dp"
            android:background="@drawable/subtitle_background_gradient"
            android:clipChildren="false"
            android:clipToPadding="false"
            android:orientation="horizontal">

        <ImageView
            android:clipToPadding="false"
            android:id="@+id/category_thumbnail"
            android:layout_width="120dp"
            android:layout_height="120dp"
            android:layout_marginLeft="24dp"
            android:layout_marginStart="24dp"
            android:layout_marginTop="16dp" />

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:layout_marginLeft="29dp"
            android:orientation="vertical">

            <TextView
                android:id="@+id/category_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="Kolory"
                android:textColor="#FFFFFF"
                android:textSize="20sp"
                android:textStyle="bold" />

            <TextView
                android:id="@+id/category_items"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="1000 wallpapers"
                android:textColor="#FFFFFF"
                android:textSize="15sp" />
        </LinearLayout>
        </LinearLayout>
    </com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader>

header.attachTo(recyclerView,true);


I tried but it didn't help

**Comment by blipinsk** [comment]
Go with the `adapter` that can inflate mutliple types of `Views`. For example [this one](https://github.com/Karumi/HeaderRecyclerView). Trying to implement `RecyclerViewHeader` that overlaps `RecyclerView` items will produce more and more issues (disabling clipping will interfere with the way `RecyclerViewHeader` calculates height of the header).
