### ISSUE TITLE
android.support.v4.widget.SwipeRefreshLayout with RecyclerViewHeader

### ISSUE THREAD

**Issue by stasbar** [blipinsk/RecyclerViewHeader#26]
Hi. When I add SwipeRefreshLayout, the Header disappear. How to solve this problem ?

    <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:tools="http://schemas.android.com/tools"
     android:layout_width="match_parent"
     android:layout_height="match_parent"
     android:orientation="vertical"
     tools:context="com.stasbar.gabi4k.category.fragments.CategoryFragment">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/fragment_category_swipe_refresh_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <android.support.v7.widget.RecyclerView
            android:layout_gravity="center_horizontal|top"
            android:id="@+id/recycler_view_spec_category"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
        <com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader
            android:layout_gravity="center_horizontal|top"
            android:id="@+id/header"
            android:layout_height="80dp"
            android:layout_width="match_parent"
            android:clipChildren="false"
            android:clipToPadding="false">
            <LinearLayout
                android:id="@+id/category_subtitle_root"
                android:layout_width="match_parent"
                android:layout_height="80dp"
                android:background="@drawable/subtitle_background_gradient"
                android:orientation="horizontal">

                <ImageView
                    android:id="@+id/category_thumbnail"
                    android:layout_width="80dp"
                    android:layout_height="80dp"
                    android:layout_marginLeft="24dp" />

                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:layout_marginLeft="29dp"
                    android:orientation="vertical">

                    <TextView
                        android:id="@+id/category_name"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="Kolory"
                        android:textColor="#FFFFFF"
                        android:textSize="20sp"
                        android:textStyle="bold" />

                    <TextView
                        android:id="@+id/category_items"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="1000 wallpapers"
                        android:textColor="#FFFFFF"
                        android:textSize="15sp" />
                </LinearLayout>
            </LinearLayout>
        </com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader>
    </android.support.v4.widget.SwipeRefreshLayout>
</FrameLayout>

**Comment by blipinsk** [comment]
Try the layout architecture from [here].(https://github.com/blipinsk/RecyclerViewHeader/issues/19#issuecomment-135731288)

**Comment by leon2017** [comment]
sorry , SwipeRefreshLayout ---->refresh --->indexoutofException
