### ISSUE TITLE
viewpager

### ISSUE THREAD

**Issue by Shubham1992** [blipinsk/RecyclerViewHeader#27]
How Do I add viewpager to the header...pleaseeeee suggest...I have put the viewpager in xml and in the java code as well...the viewpager is getting identified by code but IT IS NOT CHANGING VIEWS ON HORIZONTAL SCROLL.

**Comment by blipinsk** [comment]
You won't be able to do that. 

> [You need to bare in mind that the library is created to be used with relatively simple headers.](https://github.com/blipinsk/RecyclerViewHeader#limitations)

I don't consider `ViewPager` a simple header. Implementing a touch management that would handle this type of `View` is an overkill for me.

Use an `adapter` that can inflate a multiple types of `Views`.
