### ISSUE TITLE
Add footer to a RecyclerView

### ISSUE THREAD

**Issue by kamilwlf** [blipinsk/RecyclerViewHeader#3]
Are you planning to add a footer in the future?

**Comment by blipinsk** [comment]
I'm invastigating the possibilities to do a `Footer` library in a similar manner. If I do decide to create it, it surely won't be a part of [`RecyclerViewHeader`](https://github.com/blipinsk/RecyclerViewHeader) library. It will be a separate project.

Don't expect any result of my *invastigation* soon... Right now there are much more important things to do with this library than creating a new one. 

Feel free to **star** or start **watch**ing this project to be up to date with any new features.

**Comment by blipinsk** [comment]
If you run the *sample* project you will see that actually **can** do a footer with this library (in a bit hacky way).

You would have to use `setReversedLayout(true)` on your `LayoutManager`and reverse the order of data in the array that is used to fill the adapter.
