### ISSUE TITLE
IntelliJ files in the repo

### ISSUE THREAD

**Issue by vkotovv** [blipinsk/RecyclerViewHeader#31]
Maybe you should get rid of *.iml files in the repo? They are recreated after project import in Android Studio. And diffs look better without changes in Studio files. Take a look at [Picasso .gitignore](https://github.com/square/picasso/blob/master/.gitignore).

**Comment by blipinsk** [comment]
Sure, why not. Will do that. Thanks :+1:

**Comment by blipinsk** [comment]
Done. Cheers! :+1:

**Comment by vkotovv** [comment]
Thank you!
