### ISSUE TITLE
How can I detach header?

### ISSUE THREAD

**Issue by silviahisham** [blipinsk/RecyclerViewHeader#32]
I have a recycler view which changes its layout manager on a click of button ( List and grid), if I attach the header again for the second time, it adds extra space underneath it each time, so I need to detach it each time I change the layout manager, and then attach it again.

**Comment by blipinsk** [comment]
I do not plan to introduce a way to detach the header. You can try to do it yourself. The empty space is probably the `HeaderItemDecoration` that is left inside the `RecyclerView` after the previous attaching.
