### ISSUE TITLE
After using your instructions under ReadMe, no header is displayed

### ISSUE THREAD

**Issue by jagan999** [blipinsk/RecyclerViewHeader#33]

**Comment by blipinsk** [comment]
Could you paste some of your code?

**Comment by rajatpundir** [comment]
<androidx.recyclerview.widget.RecyclerView
            android:id="@+id/recycler_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:scrollbars="vertical"/>

    <com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader
            android:id="@+id/header"
            android:layout_width="match_parent"
            android:layout_height="100dp">

        <TextView
                android:id="@+id/header_text_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="WHATEVER"
                android:textSize="36sp" />

For me the header is being displayed above the recycler view, but no text appears inside header.

**Comment by rajatpundir** [comment]
var gridLayoutManager = GridLayoutManager(context, 3)
recycler_view.layoutManager = gridLayoutManager
header.attachTo(recycler_view_home_playlists)
adapter = RecycleViewAdapterPlaylists(context, items, this)
        recycler_view_home_playlists.adapter = adapter

**Comment by rajatpundir** [comment]
Fixed it, I had not noticed that header needs to be above the recycler view in XML.

**Comment by rajatpundir** [comment]
But I have other problem, the recycler view has a bit of spacing at the top which doesn't seem to go away it is scrolled.

**Comment by rajatpundir** [comment]
Fixed the above issue, I had to move the header and recycler view inside a constraint layout from the linear layout.
