### ISSUE TITLE
The lib is not compatible for Refresh data, How can I find out the RecyclerView is arrive at the Top?

### ISSUE THREAD

**Issue by ityancs** [blipinsk/RecyclerViewHeader#36]
I respect for author's idea, I plan to use this lib to add a header, but i find out that is not compatible for PullToRefresh and SwipeToRefreshLayout etc..

**Comment by ityancs** [comment]
I slove it by refactor the pull refresh ,but wish this lib can compatible for refresh data

**Comment by blipinsk** [comment]
First of all, the library works perfectly fine with SwipeRefreshLayout. Just use [this](https://github.com/blipinsk/RecyclerViewHeader/issues/19#issuecomment-135731288) architecture of your layout.

Second of all what do you mean by "refresh data"?

**Comment by ityancs** [comment]
I'm sorry,I tryed SwipeRefreshLayout ,It's ok! I find another problem with this lib, It's probably the header can't add ViewPager? I used a AutoScrollViewPager,thanks for your response!

**Comment by blipinsk** [comment]
You're clearly missing the point of the library. Please read the [**Limitations** ](https://github.com/blipinsk/RecyclerViewHeader/blob/master/README.md#limitations) section of **Readme**. 

> [...] library is created to be used with relatively simple headers.

> if your header uses [...] a complicated Touch management system I advice you not to use RecyclerViewHeader, but a proper RecyclerView Adapter that incorporates inflating multiple types of views [...]

I consider a `ViewPager` a layout that is using a complicated `Touch` management system.

**Comment by ityancs** [comment]
thanks, sorry for that!

**Comment by blipinsk** [comment]
Don't worry about that :smile: Thanks
