### ISSUE TITLE
Deprecated method setOnScrollListener should not be used

### ISSUE THREAD

**Issue by jakubkrolewski** [blipinsk/RecyclerViewHeader#38]
The RecyclerViewHeader class uses the deprecated RecyclerView method setOnScrollListener.
The method addOnScrollListener should be used instead.
Current behaviour makes the RecyclerViewHeader class useless in layouts when another OnScrollListener is needed.

**Comment by blipinsk** [comment]
Ow, I'm sorry that's an oversight of mine. The code has beed corrected a long time ago, but I guess I forgot to release the updated version... let me fix that.

**Comment by blipinsk** [comment]
I included the change in Release 1.2.1. It should be visible in Maven Central in few hours. Thanks

**Comment by jakubkrolewski** [comment]
Works like a charm, thanks :)
