### ISSUE TITLE
Header is not aligned correctly when screen orientation is changed

### ISSUE THREAD

**Issue by jakubkrolewski** [blipinsk/RecyclerViewHeader#41]
Steps to reproduce:
1. Remove `android:screenOrientation="portrait"` from the sample app manifest to enable support for origination changes.
2. Scroll the list a little bit
3. Rotate the screen

Result:
The header is not aligned correctly. It overlaps with list items.

**Comment by blipinsk** [comment]
Dupe of #16

**Comment by blipinsk** [comment]
Steps to reproduce are different than in #16 but the underlying issue is the same.
