### ISSUE TITLE
RecyclerView in Fragment

### ISSUE THREAD

**Issue by westito** [blipinsk/RecyclerViewHeader#44]
When Fragment restores its state (and also restores RecyclerView scroll state), the header inicializes at the restored statet and will stuck in the middle of list.

**Comment by blipinsk** [comment]
Hi, are you using second version of the library (2.0.0)? Can you paste some code, because it's working for me correctly when reusing fragments with the `RecyclerView`.

**Comment by westito** [comment]
Sorry. I used version 1.2.1. After I post the issue I seen the new version. Because it has new library name (appended 2), the dependency updater script not showed the new version.

**Comment by blipinsk** [comment]
That's fine, it has the new package (and maven groupId/artifactId) on purpose. So you can use both versions if you're migrating your entire project to a new version. Can you try with the new one?

**Comment by westito** [comment]
With the new version it works like a charm

**Comment by blipinsk** [comment]
:+1:
