### ISSUE TITLE
scroll conflict

### ISSUE THREAD

**Issue by panda912** [blipinsk/RecyclerViewHeader#45]
touch header and scroll， the view will be jump

**Comment by panda912** [comment]
if (recyclerWantsTouch && ev.getAction() == MotionEvent.ACTION_DOWN) {
            downTranslation = calculateTranslation();
}

change ACTION_DOWN to ACTION_MOVE,it work ok！

**Comment by blipinsk** [comment]
This bug has been fixed as a part of Release 2.0.1

Thanks for the contribution! 👍
