### ISSUE TITLE
when the header's height exceed the screen height,can not be displayed in full.

### ISSUE THREAD

**Issue by Carpten** [blipinsk/RecyclerViewHeader#47]
For EXAMPLE:

    <com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader
        android:id="@+id/header"
        android:layout_width="match_parent"
        android:layout_height="warp_content"
        android:layout_gravity="center_horizontal|top">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="3000dp"
            android:layout_centerInParent="true"
            android:text="header"/>

    </com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader>

**Comment by KimJihyunRiun** [comment]
I have same issue, but can't find solution.
Does anyone fix the problem?

**Comment by blipinsk** [comment]
If you look at the `/sample` app, you can see the [example for the header that is exceeding screen size](https://github.com/blipinsk/RecyclerViewHeader/blob/master/sample/src/main/java/com/bartoszlipinski/recyclerviewheader2/sample/fragment/SampleListHugeHeaderFragment.java). 

It works, but I must say that it won't be supported any more in the nearest future. The problem with those headers is that if there's no items in the adapter, you wouldn't be able to scroll the header.

**Comment by blipinsk** [comment]
Headers that exceed screen height (for `vertical` `RecyclerView`) or width (for `horizontal` `RecyclerView`) are no longer supported.
