### ISSUE TITLE
can not use with SwipRefreshView

### ISSUE THREAD

**Issue by puppet2436** [blipinsk/RecyclerViewHeader#49]
RecyclerViewHeader cover SwipRefreshLayout Progress View, or SwipRefreshLayout cover RecyslerViewHeader

**Comment by blipinsk** [comment]
Try the layout architecture from [here](https://github.com/blipinsk/RecyclerViewHeader/issues/19#issuecomment-135731288).

**Comment by blipinsk** [comment]
@puppet2436 did that layout architecture help you?
