### ISSUE TITLE
Doesn't work on reversed layout.

### ISSUE THREAD

**Issue by codevalley** [blipinsk/RecyclerViewHeader#50]
It works fine when the layout it straight, but when we set
`mLinearLayoutManager.setReverseLayout(reverse);`
 `mLinearLayoutManager.setStackFromEnd(reverse);`
then, the header gets drawn from the middle of the first item. I tried tinkering around with the code, but couldn't spend much time on figuring out the issue.

**Comment by blipinsk** [comment]
Library deprecated. No new development will be taking place.
