### ISSUE TITLE
Set Header Height as a wrap_content

### ISSUE THREAD

**Issue by pinvisible** [blipinsk/RecyclerViewHeader#52]
Hello, loved using your library.

One issue i found.

- If we set header height as a wrap_content, then recyclerview does not display full header. Some part of header disappears. I think in the case of wrap_content and if content is bigger then screen height, right now you are considering screen height as a header.

Can you please fix this?

Thanks

**Comment by blipinsk** [comment]
Hi @pinvisible, unfortunately `RecyclerViewHeader` is [not to be used with headers with height bigger than screen size](https://github.com/blipinsk/RecyclerViewHeader#limitations). This is a limitation of the library I created and I do not plan to "fix" it.

Enabling bigger headers introduces many problems with library concepts, and headers bigger than screen size usually contradict a different principle of the library (header should be relatively simple).

Cheers!
