### ISSUE TITLE
Header smaller than screen height,but larger than half height init shown is not right

### ISSUE THREAD

**Issue by ityancs** [blipinsk/RecyclerViewHeader#53]
Header smaller than screen height,but larger than half height init shown is not right,
but when i touch the screen ,it will show the right layout.
Is there any suggestion to solve the problem?
by the way ,RecyclerViewHeader is great lib for RecyclerView, Looking forward to your reply.

**Comment by ityancs** [comment]
I finally find the problem, when the RecyclerView item view call requestFocus to get focus may cause this problem. I will remove the request focus code, but I wonder why this can cause this problem?

**Comment by blipinsk** [comment]
Library deprecated. No new development will be taking place.
