### ISSUE TITLE
RecyclerView seems to be intercepting scroll events?

### ISSUE THREAD

**Issue by CHPraxis** [blipinsk/RecyclerViewHeader#57]
Hello- I'm trying to put a ViewPager as my header.  However, I can't seem to swipe horizontally in the ViewPager- I assume that the RecyclerView is intercepting my touch inputs.  How do I resolve that?

**Comment by blipinsk** [comment]
Hi, I'm sorry but scrollable elements are not supported, read more in the [Limitations](https://github.com/blipinsk/RecyclerViewHeader#limitations) section.
