### ISSUE TITLE
Header attach issue

### ISSUE THREAD

**Issue by arpitjoshi08** [blipinsk/RecyclerViewHeader#59]
Hello , I am getting one issue that my recycler view height and width fill parent and my header put on top of screen ...know when I attach header and load list, the list first item hide behind the header and for a second and look so awkward and   then it's come on our proper position below the header ....how can I resolved this issue ? I tried to put recycler view below the header but it take so much space

**Comment by blipinsk** [comment]
Library deprecated. No new development will be taking place.
