### ISSUE TITLE
Not correct header

### ISSUE THREAD

**Issue by dikhawk** [blipinsk/RecyclerViewHeader#60]
If you change layoutManager for RV, header viewed not correct. (Sample new GridLayoutManager(getContext(), 1) and changed new GridLayoutManager(getContext(), 2)) I fix it added to HeaderItemDecoration::getItemOffsets() firstRowSpan = layoutManager.getFirstRowSpan();

Sorry for my English, and Thx for libary

**Comment by blipinsk** [comment]
Library deprecated. No new development will be taking place.
