### ISSUE TITLE
Currently, NOT already aligned RecyclerViewHeader can only be used for RecyclerView with a parent of one of types: LinearLayout, FrameLayout, RelativeLayout.

### ISSUE THREAD

**Issue by HyperSimon** [blipinsk/RecyclerViewHeader#61]
And the parent of my RecyclerView is a SwipeRefreshLayout, what should i do?

**Comment by blipinsk** [comment]
Try [this](https://github.com/blipinsk/RecyclerViewHeader/issues/19#issuecomment-135731288) architecture.
