### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView.onInterceptTouchEvent(android.view.MotionEvent)' on a null object reference

### ISSUE THREAD

**Issue by yongyu0102** [blipinsk/RecyclerViewHeader#62]
i used version "compile 'com.bartoszlipinski.recyclerviewheader:library:1.2.0'"

crash error info:

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.RecyclerView.onInterceptTouchEvent(android.view.MotionEvent)' on a null object reference

**Comment by blipinsk** [comment]
1. You should be using the second version
`compile 'com.bartoszlipinski:recyclerviewheader2:2.0.1'`
2. If for some reason you don't want to use the second version, at least try
`compile 'com.bartoszlipinski:recyclerviewheader:1.2.1'`

**Comment by zpc5925439** [comment]
bro,I use the version recyclerviewheader2:2.0.1',but it still crashed by this ,how could I do?Ths

**Comment by blipinsk** [comment]
Library deprecated. No new development will be taking place.
