### ISSUE TITLE
How to work setonclicklister for header.

### ISSUE THREAD

**Issue by faziltm** [blipinsk/RecyclerViewHeader#65]
This code is working and very helpful for me. I really thanking you. I want to add setonclicklistener on header. How it possible? 
For example when i click on the header then it goes another fragment .
Is it possible?

**Comment by blipinsk** [comment]
Hi, you should be able to do that out of the box. Can you post your layout?

**Comment by faziltm** [comment]
My question is posted in http://stackoverflow.com/questions/42097788/android-setonclicklistener-is-not-working-recycler-header

**Comment by faziltm** [comment]
My layout code is fragment_sample.xml

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             android:layout_width="match_parent"
             android:layout_height="match_parent"
             android:paddingLeft="@dimen/title_padding"
             android:paddingRight="@dimen/title_padding">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal|top"/>

    <com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader
        android:id="@+id/header"
        android:layout_width="match_parent"
        android:layout_height="@dimen/header_height"
        android:layout_gravity="center_horizontal|top"
        android:layout_margin="@dimen/recycler_divider_width"
        android:background="@drawable/rounded_background_header">

        <Button
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_centerInParent="true"
            android:background="?selectableItemBackgroundBorderless"
            android:fontFamily="sans-serif-light"
            android:textAllCaps="false"
            android:text="@string/header"
            android:textColor="@color/clouds"
            android:textSize="20sp"/>

    </com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader>

</FrameLayout>

**Comment by blipinsk** [comment]
could you post your entire layout?

**Comment by blipinsk** [comment]
nvm, I updated your comment to correctly include `code` (it wasn't showing your `FrameLayout`)

**Comment by blipinsk** [comment]
I don't see a point in talking in two places at the same time. I'm closing the issue, heading to StackOverflow.
