### ISSUE TITLE
StaggeredGridLayoutManager

### ISSUE THREAD

**Issue by keithics** [blipinsk/RecyclerViewHeader#67]
Is StaggeredGrid supported? I saw the code but it is commented.

                private LayoutManagerDelegate(@NonNull RecyclerView.LayoutManager manager) {
                    final Class<? extends RecyclerView.LayoutManager> managerClass = manager.getClass();
                    if (managerClass == LinearLayoutManager.class) { //not using instanceof on purpose
                        linear = (LinearLayoutManager) manager;
                        grid = null;
                        staggeredGrid = null;
                    } else if (managerClass == GridLayoutManager.class) {
                        linear = null;
                        grid = (GridLayoutManager) manager;
                        staggeredGrid = null;
        //            } else if (manager instanceof StaggeredGridLayoutManager) { //TODO: 05.04.2016 implement staggered
        //                linear = null;
        //                grid = null;
        //                staggeredGrid = (StaggeredGridLayoutManager) manager;
                    } else {
                        throw new IllegalArgumentException("Currently RecyclerViewHeader supports only LinearLayoutManager and GridLayoutManager.");
                    }
                }

**Comment by blipinsk** [comment]
There was a support for `StaggeredGridLayoutManager` in the version 1 of the library.
With the version 2 I _temporarily_ removed it and was planning to bring it back in the future. Unfortunately I decided to retire the library and I never really brought `StaggeredGridLayoutManager` support back.

I will try to look (this week) if I can do it with some simple code. I don't wanna spend hours changing the code I don't see any future with.

**Comment by keithics** [comment]
I understand, thank you for your time.

**Comment by blipinsk** [comment]
Library deprecated. No new development will be taking place.
