### ISSUE TITLE
unaligned in viewpager

### ISSUE THREAD

**Issue by rehacktive** [blipinsk/RecyclerViewHeader#7]
My app structure is a list of fragments inside a Viewpager.
Each fragment has a recyclerview + an header, set up in this way:

      header = (RecyclerViewHeader) view.findViewById(R.id.header);
        header.attachTo(mRecyclerView, true);

it works perfectly, but when I switch to another fragment (let's say two pages, so when the first fragment goes off the "memory") and I go back to this fragment, everything is not more aligned (header and recyclerview content are messed up).

I can provide code but it would be very helpful to know if you experience the same issue and if you have a solution for this.

thanks!

**Comment by MohHeader** [comment]
I have something like this, but not within ViewPager.
A very normal Header,

and when I scroll so far down, and return to up,
I found my Header ( disappeared but it's space still there ) or ( moved a little bit upward with a space between them )

**Comment by blipinsk** [comment]
@MohHeader are you using `setOnScrollListener` for your `RecyclerView`?

**Comment by MohHeader** [comment]
No,

Here is the code.
~~~~java
        mRecyclerView = (RecyclerView) findViewById(R.id.my_recycler_view);
        StaggeredGridLayoutManager mLayoutManager = new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL);
        mRecyclerView.addItemDecoration(new ProductsRecyclerView.SpacesItemDecoration(5, true));
        mRecyclerView.setLayoutManager(mLayoutManager);
        mAdapter = new ProductsAdapter(this, products);
        RecyclerViewHeader header = (RecyclerViewHeader) findViewById(R.id.header);
        header.attachTo(mRecyclerView, true);
        mRecyclerView.setAdapter(mAdapter);
~~~~

and for ProductsRecyclerView
~~~~java
        StaggeredGridLayoutManager mLayoutManager = new StaggeredGridLayoutManager(2, StaggeredGridLayoutManager.VERTICAL);
        addItemDecoration(new SpacesItemDecoration(5));
        setLayoutManager(mLayoutManager);
~~~~

SpacesItemDecoration is just an ItemDecoration that gives some space between items,

For the XML,

~~~~xml
<android.support.v7.widget.RecyclerView
        android:id="@+id/my_recycler_view"
        android:scrollbars="vertical"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:scrollbarStyle="outsideOverlay"
        android:layout_gravity="center_horizontal|top"/>

    <com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader
        android:id="@+id/header"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal|top">
        <com.espace.pfamilies.views.custom.StoreHeaderView
            android:id="@+id/store_details"
            android:layout_width="match_parent"
            <android:layout_height="wrap_content"
            <android:layout_marginBottom="10dp"/>


    </com.bartoszlipinski.recyclerviewheader.RecyclerViewHeader>
~~~~

**Comment by blipinsk** [comment]
This refers to the same problem as Issue #16. Let me mark this topic as a duplicate (although the other one is a duplicate to be precise), because #16 better specifies the reason for the problem. Thanks.
