### ISSUE TITLE
How to hide header when search items

### ISSUE THREAD

**Issue by kingnightdrifter** [blipinsk/RecyclerViewHeader#71]
Hello there Hope you are doing good,

I am facing an issue that how to hide header when apply search on recyclerview. My sample code is here bellow. Please pause your comment really appreciate to you.

 <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="45dp"
        android:focusableInTouchMode="true">
    <android.support.v7.widget.SearchView
        android:id="@+id/floating_search_view"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        app:defaultQueryHint="Some Text Here"
        app:queryHint="Search Restaurant"
        app:iconifiedByDefault="false"
        app:searchIcon="@drawable/search_icon"
        style="@style/SearchViewMy"
        android:queryBackground="@android:color/transparent"
        android:focusableInTouchMode="true"/>
    </LinearLayout>

        <android.support.v4.widget.SwipeRefreshLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/refresh_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

    <android.support.percent.PercentRelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/recycler_view_restaurant">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/restaurant_recycler_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            android:clipToPadding="false"
           />

        <com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader
            android:id="@+id/header"
            app:layout_widthPercent="100%"
            app:layout_heightPercent="38%"
            android:layout_gravity="center_horizontal|top">

            <include layout="@layout/row_item_view_pager"></include>

        </com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader>

    </android.support.percent.PercentRelativeLayout>

        </android.support.v4.widget.SwipeRefreshLayout>

</LinearLayout>

**Comment by blipinsk** [comment]
please correct the posted layout xml
Right now it doesn't really make any sense (too many `LinearLayouts`).

**Comment by blipinsk** [comment]
Library deprecated. No new development will be taking place.
