### ISSUE TITLE
Not Work Well on Switch GridLayoutManager To LinearLayoutManager

### ISSUE THREAD

**Issue by dazeGitHub** [blipinsk/RecyclerViewHeader#75]
When I switch GridLayoutManager  To LinearLayoutManager,Some item show bad ,Code like this:

class MainActivity : Activity() {

    private var recyclerHeader: RecyclerViewHeader? = null
    private var recyclerView: RecyclerView? = null
    private var adapter: TestAdapter? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        recyclerView = findViewById(R.id.recyclerView)
        recyclerHeader = findViewById(R.id.header) as RecyclerViewHeader

        // 设置adapter
        adapter = TestAdapter(R.layout.item_test, null)
        val gridLayoutManager = GridLayoutManager(applicationContext, 4, LinearLayoutManager.VERTICAL, false)
        recyclerView?.layoutManager = gridLayoutManager
        recyclerView?.setAdapter(adapter)
        val items = ArrayList<String>()
        for (i in 0 until 16) {
            items.add("原始数据Init$i")
        }
        adapter?.setNewData(items)
        recyclerHeader?.attachTo(recyclerView!!)

        btn_grid?.setOnClickListener {
            recyclerView?.layoutManager = GridLayoutManager(this, 3)
//            var girdDecoration = GridItemDecoration(20, 30)
//            recyclerView?.addItemDecoration(girdDecoration)

            val items = ArrayList<String>()
            for (i in 0 until 16) {
                items.add("原始数据Grid$i")
            }
            adapter?.setNewData(items)
            recyclerHeader?.attachTo(recyclerView!!)
        }

        btn_linear?.setOnClickListener {
            recyclerView?.layoutManager = LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false)

            val items = ArrayList<String>()
            for (i in 0 until 16) {
                items.add("原始数据Linear$i")
            }
            adapter?.setNewData(items)
            recyclerHeader?.attachTo(recyclerView!!)
        }
    }
}

layout like this:

<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#ff0000"
        android:paddingLeft="10dp"
        android:paddingRight="10dp"
        android:paddingTop="15dp"
        />

    <com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader
        android:id="@+id/header"
        android:layout_width="match_parent"
        android:layout_height="400dp"
        android:layout_gravity="center_horizontal|top"
        android:background="#0000ff"
        android:visibility="gone"
        >

        <Button
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_centerInParent="true"
            android:background="#00ff00"
            android:text="这是头"
            android:textAllCaps="false"
            android:textColor="#ffffff"
            android:textSize="20sp"
            />

    </com.bartoszlipinski.recyclerviewheader2.RecyclerViewHeader>

    <Button
        android:id="@+id/btn_grid"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Grid"
        />

    <Button
        android:id="@+id/btn_linear"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Linear"
        app:layout_constraintRight_toRightOf="parent"
        />

</android.support.constraint.ConstraintLayout>

**Comment by dazeGitHub** [comment]
I resolve it !! ,But I still don't know why HeaderItemDecoration 里的  firstRowSpan 会变，The solution down:

 private class HeaderItemDecoration extends RecyclerView.ItemDecoration {
     //..
     @Override
     public void getItemOffsets(Rect outRect, View view, RecyclerView parent, RecyclerView.State state) {
           super.getItemOffsets(outRect, view, parent, state);
            // assign the firstRowSpan  again
            firstRowSpan = layoutManager.getFirstRowSpan();
            //...
     }
}

**Comment by blipinsk** [comment]
Library deprecated. No new development will be taking place.
